---
- name: Restart Tomcat Application
- hosts: all
  become: yes
  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-server
        - tomcat
        - memcached
        - redis

    

